/** Snapshot of the seeded exercise catalog (src/lib/db/seed.ts) for unit tests. */
import type { ExerciseRecord } from "@/lib/ai/plan-rules";

export const CATALOG: ExerciseRecord[] = [
  { id: 1, name: "Barbell Bench Press", category: "barbell", primaryMuscleGroup: "chest" },
  { id: 2, name: "Incline Barbell Bench Press", category: "barbell", primaryMuscleGroup: "chest" },
  { id: 3, name: "Dumbbell Bench Press", category: "dumbbell", primaryMuscleGroup: "chest" },
  { id: 4, name: "Incline Dumbbell Bench Press", category: "dumbbell", primaryMuscleGroup: "chest" },
  { id: 5, name: "Dumbbell Fly", category: "dumbbell", primaryMuscleGroup: "chest" },
  { id: 6, name: "Cable Fly", category: "cable", primaryMuscleGroup: "chest" },
  { id: 7, name: "Machine Chest Press", category: "machine", primaryMuscleGroup: "chest" },
  { id: 8, name: "Pec Deck", category: "machine", primaryMuscleGroup: "chest" },
  { id: 9, name: "Push-Up", category: "bodyweight", primaryMuscleGroup: "chest" },
  { id: 10, name: "Dips (Chest)", category: "bodyweight", primaryMuscleGroup: "chest" },
  { id: 11, name: "Barbell Row", category: "barbell", primaryMuscleGroup: "back" },
  { id: 12, name: "Deadlift", category: "barbell", primaryMuscleGroup: "back" },
  { id: 13, name: "Pull-Up", category: "bodyweight", primaryMuscleGroup: "back" },
  { id: 14, name: "Chin-Up", category: "bodyweight", primaryMuscleGroup: "back" },
  { id: 15, name: "Lat Pulldown", category: "cable", primaryMuscleGroup: "back" },
  { id: 16, name: "Seated Cable Row", category: "cable", primaryMuscleGroup: "back" },
  { id: 17, name: "Dumbbell Row", category: "dumbbell", primaryMuscleGroup: "back" },
  { id: 18, name: "T-Bar Row", category: "barbell", primaryMuscleGroup: "back" },
  { id: 19, name: "Face Pull", category: "cable", primaryMuscleGroup: "back" },
  { id: 20, name: "Machine Row", category: "machine", primaryMuscleGroup: "back" },
  { id: 21, name: "Overhead Press", category: "barbell", primaryMuscleGroup: "shoulders" },
  { id: 22, name: "Dumbbell Shoulder Press", category: "dumbbell", primaryMuscleGroup: "shoulders" },
  { id: 23, name: "Lateral Raise", category: "dumbbell", primaryMuscleGroup: "shoulders" },
  { id: 24, name: "Front Raise", category: "dumbbell", primaryMuscleGroup: "shoulders" },
  { id: 25, name: "Reverse Fly", category: "dumbbell", primaryMuscleGroup: "shoulders" },
  { id: 26, name: "Arnold Press", category: "dumbbell", primaryMuscleGroup: "shoulders" },
  { id: 27, name: "Cable Lateral Raise", category: "cable", primaryMuscleGroup: "shoulders" },
  { id: 28, name: "Machine Shoulder Press", category: "machine", primaryMuscleGroup: "shoulders" },
  { id: 29, name: "Barbell Curl", category: "barbell", primaryMuscleGroup: "biceps" },
  { id: 30, name: "Dumbbell Curl", category: "dumbbell", primaryMuscleGroup: "biceps" },
  { id: 31, name: "Hammer Curl", category: "dumbbell", primaryMuscleGroup: "biceps" },
  { id: 32, name: "Preacher Curl", category: "barbell", primaryMuscleGroup: "biceps" },
  { id: 33, name: "Cable Curl", category: "cable", primaryMuscleGroup: "biceps" },
  { id: 34, name: "Incline Dumbbell Curl", category: "dumbbell", primaryMuscleGroup: "biceps" },
  { id: 35, name: "Tricep Pushdown", category: "cable", primaryMuscleGroup: "triceps" },
  { id: 36, name: "Overhead Tricep Extension", category: "dumbbell", primaryMuscleGroup: "triceps" },
  { id: 37, name: "Skull Crusher", category: "barbell", primaryMuscleGroup: "triceps" },
  { id: 38, name: "Dips (Tricep)", category: "bodyweight", primaryMuscleGroup: "triceps" },
  { id: 39, name: "Cable Overhead Extension", category: "cable", primaryMuscleGroup: "triceps" },
  { id: 40, name: "Close-Grip Bench Press", category: "barbell", primaryMuscleGroup: "triceps" },
  { id: 41, name: "Barbell Squat", category: "barbell", primaryMuscleGroup: "quads" },
  { id: 42, name: "Front Squat", category: "barbell", primaryMuscleGroup: "quads" },
  { id: 43, name: "Leg Press", category: "machine", primaryMuscleGroup: "quads" },
  { id: 44, name: "Leg Extension", category: "machine", primaryMuscleGroup: "quads" },
  { id: 45, name: "Goblet Squat", category: "dumbbell", primaryMuscleGroup: "quads" },
  { id: 46, name: "Hack Squat", category: "machine", primaryMuscleGroup: "quads" },
  { id: 47, name: "Bulgarian Split Squat", category: "dumbbell", primaryMuscleGroup: "quads" },
  { id: 48, name: "Walking Lunge", category: "dumbbell", primaryMuscleGroup: "quads" },
  { id: 49, name: "Romanian Deadlift", category: "barbell", primaryMuscleGroup: "hamstrings" },
  { id: 50, name: "Leg Curl", category: "machine", primaryMuscleGroup: "hamstrings" },
  { id: 51, name: "Seated Leg Curl", category: "machine", primaryMuscleGroup: "hamstrings" },
  { id: 52, name: "Stiff-Leg Deadlift", category: "barbell", primaryMuscleGroup: "hamstrings" },
  { id: 53, name: "Nordic Hamstring Curl", category: "bodyweight", primaryMuscleGroup: "hamstrings" },
  { id: 54, name: "Hip Thrust", category: "barbell", primaryMuscleGroup: "glutes" },
  { id: 55, name: "Cable Pull-Through", category: "cable", primaryMuscleGroup: "glutes" },
  { id: 56, name: "Glute Bridge", category: "bodyweight", primaryMuscleGroup: "glutes" },
  { id: 57, name: "Cable Kickback", category: "cable", primaryMuscleGroup: "glutes" },
  { id: 58, name: "Standing Calf Raise", category: "machine", primaryMuscleGroup: "calves" },
  { id: 59, name: "Seated Calf Raise", category: "machine", primaryMuscleGroup: "calves" },
  { id: 60, name: "Donkey Calf Raise", category: "machine", primaryMuscleGroup: "calves" },
  { id: 61, name: "Plank", category: "bodyweight", primaryMuscleGroup: "core" },
  { id: 62, name: "Crunch", category: "bodyweight", primaryMuscleGroup: "core" },
  { id: 63, name: "Hanging Leg Raise", category: "bodyweight", primaryMuscleGroup: "core" },
  { id: 64, name: "Cable Woodchop", category: "cable", primaryMuscleGroup: "core" },
  { id: 65, name: "Ab Wheel Rollout", category: "other", primaryMuscleGroup: "core" },
  { id: 66, name: "Russian Twist", category: "bodyweight", primaryMuscleGroup: "core" },
  { id: 67, name: "Dead Bug", category: "bodyweight", primaryMuscleGroup: "core" },
  { id: 68, name: "Pallof Press", category: "cable", primaryMuscleGroup: "core" },
  { id: 69, name: "Wrist Curl", category: "dumbbell", primaryMuscleGroup: "forearms" },
  { id: 70, name: "Reverse Wrist Curl", category: "dumbbell", primaryMuscleGroup: "forearms" },
  { id: 71, name: "Treadmill Running", category: "cardio", primaryMuscleGroup: "full_body" },
  { id: 72, name: "Rowing Machine", category: "cardio", primaryMuscleGroup: "full_body" },
  { id: 73, name: "Cycling (Stationary)", category: "cardio", primaryMuscleGroup: "full_body" },
  { id: 74, name: "Elliptical", category: "cardio", primaryMuscleGroup: "full_body" },
  { id: 75, name: "Stair Climber", category: "cardio", primaryMuscleGroup: "full_body" },
  { id: 76, name: "Jump Rope", category: "cardio", primaryMuscleGroup: "full_body" },
  { id: 77, name: "Clean and Press", category: "barbell", primaryMuscleGroup: "full_body" },
  { id: 78, name: "Kettlebell Swing", category: "other", primaryMuscleGroup: "full_body" },
  { id: 79, name: "Burpee", category: "bodyweight", primaryMuscleGroup: "full_body" },
  { id: 80, name: "Turkish Get-Up", category: "other", primaryMuscleGroup: "full_body" },
];
